const translations = {
    "en": {
        "nav_identity": "Identity",
        "nav_ecosystem": "Ecosystem",
        "nav_tech": "Tech",
        "nav_projections": "Projections",
        "hero_ecosystem": "QUANTUM FINANCE ECOSYSTEM",
        "hero_subtitle": "The Next-Gen Global Digital Dollar Infrastructure powered by Post-Quantum Security & High-Quality Liquid Assets.",
        "hero_btn": "Discover the Future",
        "id_title": "Corporate Identity",
        "id_subtitle": "Legal Status & Strategic Foundation",
        "id_reg_info": "Registered Information",
        "id_reg_desc": "Based on Certificate of Incorporation (No. 79281279)",
        "id_entity": "Entity: QUMS Group Limited (Limited by Shares)",
        "id_inc": "Incorporated: 28 November 2025 (Hong Kong)",
        "id_hq": "HQ: RM 14, 29/F, Ho King Comm Centre, Mong Kok, HK",
        "id_founder": "Founder: Song Chang Moo",
        "hkma_title": "HKMA Compliance",
        "hkma_desc": "Aligning with Hong Kong Stablecoin Regulatory Sandbox guidelines for absolute legal certainty.",
        "reserve_title": "Reserve Safety",
        "reserve_desc": "100% Cash & HQLA segregation in top-tier licensed financial institutions.",
        "eco_title": "Digital Dollar Hub",
        "eco_subtitle": "Massive RWA Collateralization & Quantum Security",
        "stat_assets": "Underlying Assets in HK",
        "stat_issuance": "Initial Targeted Issuance",
        "rel_title": "Reliability Model",
        "rel_1": "Post-Quantum Cryptography against future threats",
        "rel_2": "Segregated Trustee Custody",
        "rel_3": "Monthly External Attestations",
        "rel_4": "100% Cash & Cash Equivalents with Real-time PoR",
        "quantum_title": "Quantum Core",
        "quantum_desc": "Utilizing superposition logic for ultra-high throughput transactions & advanced risk analysis.",
        "token_title": "USDQS Token",
        "token_desc": "1:1 USD-linked stablecoin acting as a liquid reserve asset for global participants.",
        "cross_title": "Cross-border",
        "cross_desc": "Seamless core settlement layer bridging traditional finance and blockchain economies.",
        "arch_title": "Platform Architecture",
        "arch_subtitle": "Hybrid Layered Stack & Modular Contracts",
        "arch_front": "Frontend",
        "arch_front_desc": "React / Mobile App",
        "arch_gw": "Gateway",
        "arch_gw_desc": "Throttling / WAF",
        "arch_back": "Backend",
        "arch_back_desc": "FastAPI / Microservices",
        "arch_custody": "Custody",
        "arch_custody_desc": "MPC / HSM Vault",
        "bc_title": "Blockchain Layer",
        "bc_desc": "Ethereum L1 (ERC-20), Polygon Bridge, Arbitrum Scalability. Smart contracts govern Token Mint/Burn, Collateral Management, and automated Fiat-to-Token workflows.",
        "audit_title": "Audit & Oracle",
        "audit_desc": "SIEM & WORM Storage, Forensic Audit Logs. Reserve Oracles connect off-chain banking data to on-chain transparency dashboards securely.",
        "proj_title": "Growth Trajectory",
        "proj_subtitle": "5-Year Revenue Projections (Billion USD)",
        "year_1": "Year 1",
        "year_2": "Year 2",
        "year_3": "Year 3",
        "year_4": "Year 4",
        "year_5": "Year 5",
        "res_interest": "Reserve Interest (Y5)",
        "plat_fees": "Platform Fees (Y5)",
        "cum_profit": "Cumulative Profit",
        "footer_title1": "STABILITY MEETS",
        "footer_title2": "QUANTUM",
        "footer_desc": "Building the most trusted global digital dollar infrastructure with RWA-backed reliability and quantum-speed settlement.",
        "footer_corp": "QUMS Group Limited",
        "footer_corp_desc1": "Corporate Reg No: 79281279",
        "footer_corp_desc2": "Mong Kok, Hong Kong SAR",
        "footer_partners": "Partnerships",
        "footer_partners_desc1": "Supported by Dentons, DLA Piper",
        "footer_partners_desc2": "Big Four Independent Audit",
        "footer_copy": "© 2026 QUMS Group Limited. All rights reserved.",
        "lang_en": "English",
        "lang_ko": "한국어",
        "lang_zh": "中文"
    },
    "ko": {
        "nav_identity": "기업 정보",
        "nav_ecosystem": "생태계",
        "nav_tech": "기술",
        "nav_projections": "재무 전망",
        "hero_ecosystem": "퀀텀 금융 생태계",
        "hero_subtitle": "양자 내성 보안 및 고유동성 자산(HQLA)이 지원하는 차세대 글로벌 디지털 달러 인프라.",
        "hero_btn": "미래를 발견하다",
        "id_title": "기업 정체성",
        "id_subtitle": "법적 지위 및 전략적 기반",
        "id_reg_info": "등록 정보",
        "id_reg_desc": "기업 등록 증명서 기준 (No. 79281279)",
        "id_entity": "법인: QUMS Group Limited (주식회사)",
        "id_inc": "설립일: 2025년 11월 28일 (홍콩)",
        "id_hq": "본사: 홍콩 몽콕 Ho King Comm Centre 29층 14호",
        "id_founder": "창립자: 송창무",
        "hkma_title": "HKMA 규제 준수",
        "hkma_desc": "절대적인 법적 확실성을 위해 홍콩 스테이블코인 규제 샌드박스 가이드라인 준수.",
        "reserve_title": "준비금 안전성",
        "reserve_desc": "최상위 인가 금융 기관에 현금 및 고유동성 자산(HQLA) 100% 분리 보관.",
        "eco_title": "디지털 달러 허브",
        "eco_subtitle": "대규모 실물 담보(RWA) 및 양자 보안",
        "stat_assets": "홍콩 내 기초 자산",
        "stat_issuance": "초기 목표 발행량",
        "rel_title": "신뢰성 모델",
        "rel_1": "미래 위협에 대비한 양자 내성 암호",
        "rel_2": "분리된 수탁자 보관",
        "rel_3": "월 단위 외부 회계 감사",
        "rel_4": "실시간 준비금 증명(PoR)이 적용된 100% 현금 및 자산",
        "quantum_title": "퀀텀 코어",
        "quantum_desc": "초고속 트랜잭션 및 정밀한 리스크 분석을 위한 양자 컴퓨팅 논리 활용.",
        "token_title": "USDQS 토큰",
        "token_desc": "글로벌 생태계 참여자를 위한 1:1 USD 연동 안정적 디지털 자산.",
        "cross_title": "크로스보더(국경간) 결제",
        "cross_desc": "전통 금융과 블록체인 경제를 완벽하게 연결하는 핵심 결제 레이어.",
        "arch_title": "플랫폼 아키텍처",
        "arch_subtitle": "하이브리드 계층화 스택 및 모듈식 컨트랙트",
        "arch_front": "프론트엔드",
        "arch_front_desc": "React / 모바일 앱",
        "arch_gw": "게이트웨이",
        "arch_gw_desc": "스로틀링 / WAF",
        "arch_back": "백엔드",
        "arch_back_desc": "FastAPI / 마이크로서비스",
        "arch_custody": "커스터디",
        "arch_custody_desc": "MPC / HSM 금고 보안",
        "bc_title": "블록체인 레이어",
        "bc_desc": "이더리움 L1 (ERC-20), 폴리곤 브릿지, 아비트럼 확장성 지원. 스마트 컨트랙트를 통한 토큰 발행, 담보 관리 및 자동화 모델.",
        "audit_title": "감사 및 오라클",
        "audit_desc": "SIEM 및 WORM 스토리지, 보안 감사 로그. 오프체인 금융 데이터를 온체인 대시보드와 연결하는 오라클 시스템.",
        "proj_title": "성장 궤적",
        "proj_subtitle": "5개년 예상 매출 (단위: 10억 달러)",
        "year_1": "1년차",
        "year_2": "2년차",
        "year_3": "3년차",
        "year_4": "4년차",
        "year_5": "5년차",
        "res_interest": "준비금 이자 수익 (5년차)",
        "plat_fees": "플랫폼 수수료 (5년차)",
        "cum_profit": "누적 이익",
        "footer_title1": "안정성과 결합한",
        "footer_title2": "양자 기술",
        "footer_desc": "RWA 기반의 신뢰성과 양자 속도의 결제를 갖춘 최고 수준의 글로벌 디지털 달러 인프라 라인.",
        "footer_corp": "QUMS Group Limited",
        "footer_corp_desc1": "법인 등록원 번호: 79281279",
        "footer_corp_desc2": "홍콩 특별행정구 몽콕",
        "footer_partners": "파트너십",
        "footer_partners_desc1": "Dentons, DLA Piper 법률 자문",
        "footer_partners_desc2": "빅4 회계법인의 독립적인 외부 감사",
        "footer_copy": "© 2026 QUMS Group Limited. All rights reserved.",
        "lang_en": "English",
        "lang_ko": "한국어",
        "lang_zh": "中文"
    },
    "zh": {
        "nav_identity": "企業信息",
        "nav_ecosystem": "生態系統",
        "nav_tech": "技術",
        "nav_projections": "財務預測",
        "hero_ecosystem": "量子金融生態系統",
        "hero_subtitle": "由抗量子安全性和高質量流動資產 (HQLA) 支持的下一代全球數字美元基礎設施。",
        "hero_btn": "發現未來",
        "id_title": "企業形象",
        "id_subtitle": "法律地位與戰略基礎",
        "id_reg_info": "註冊信息",
        "id_reg_desc": "基於公司註冊證書 (No. 79281279)",
        "id_entity": "實體：QUMS Group Limited（股份有限公司）",
        "id_inc": "成立日期：2025年11月28日（香港）",
        "id_hq": "總部：香港旺角好景商業中心29樓14室",
        "id_founder": "創始人：Song Chang Moo",
        "hkma_title": "HKMA 合規",
        "hkma_desc": "遵守香港穩定幣監管沙盒指南，確保絕對的法律確定性。",
        "reserve_title": "儲備金安全",
        "reserve_desc": "在頂級持牌金融機構中實現 100% 現金及高質量流動資產分離託管。",
        "eco_title": "數字美元樞紐",
        "eco_subtitle": "大規模實物資產 (RWA) 擔保與量子安全",
        "stat_assets": "香港底層資產",
        "stat_issuance": "初始目標發行量",
        "rel_title": "可靠性模型",
        "rel_1": "應對未來威脅的抗量子密碼學",
        "rel_2": "分離的受託人託管",
        "rel_3": "每月外部審計證明",
        "rel_4": "具備實時準備金證明 (PoR) 的 100% 現金及現金等價物",
        "quantum_title": "量子核心",
        "quantum_desc": "利用疊加邏輯實現超高吞吐量交易和高級風險分析。",
        "token_title": "USDQS 代幣",
        "token_desc": "1:1 掛鈎美元的穩定幣，作為全球參與者的流動儲備資產。",
        "cross_title": "跨境結算",
        "cross_desc": "無縫的核心結算層，連接著傳統金融與區塊鏈數字經濟。",
        "arch_title": "平台架構",
        "arch_subtitle": "混合分層堆棧和模塊化合約",
        "arch_front": "前端",
        "arch_front_desc": "React / 移動應用",
        "arch_gw": "網關",
        "arch_gw_desc": "限流 / WAF 防火牆",
        "arch_back": "後端",
        "arch_back_desc": "FastAPI / 微服務",
        "arch_custody": "託管",
        "arch_custody_desc": "MPC / HSM 金庫",
        "bc_title": "區塊鏈層",
        "bc_desc": "乙太坊 L1 (ERC-20)、Polygon 橋接、Arbitrum 擴展性。智能合約管理代幣鑄造/銷毀、擔保管理和自動化的法幣轉換工作流。",
        "audit_title": "審計與預言機",
        "audit_desc": "SIEM 和 WORM 存儲，取證審計日誌。儲備預言機將鏈下銀行數據安全地連接到鏈上透明儀表板。",
        "proj_title": "增長軌跡",
        "proj_subtitle": "5 年收入預測（十億美元）",
        "year_1": "第 1 年",
        "year_2": "第 2 年",
        "year_3": "第 3 年",
        "year_4": "第 4 年",
        "year_5": "第 5 年",
        "res_interest": "儲備利息（第 5 年）",
        "plat_fees": "平台費用（第 5 年）",
        "cum_profit": "累計利潤",
        "footer_title1": "穩定性遇見",
        "footer_title2": "量子技術",
        "footer_desc": "構建以 RWA 背書的可靠性和量子變速度結算的最受全球信任的數字美元基礎設施。",
        "footer_corp": "QUMS 集團有限公司",
        "footer_corp_desc1": "企業註冊號：79281279",
        "footer_corp_desc2": "香港特別行政區旺角",
        "footer_partners": "合作夥伴",
        "footer_partners_desc1": "由 Dentons, DLA Piper 提供法律支持",
        "footer_partners_desc2": "四大的獨立審計",
        "footer_copy": "© 2026 QUMS Group Limited. 保留所有權利。",
        "lang_en": "English",
        "lang_ko": "한국어",
        "lang_zh": "中文"
    }
};

function changeLanguage(lang) {
    localStorage.setItem('qums_lang', lang);
    const elements = document.querySelectorAll('[data-i18n]');
    elements.forEach(el => {
        const key = el.getAttribute('data-i18n');
        if (translations[lang] && translations[lang][key]) {
            // Check if the element has inner icons or specific formatting to keep. 
            // In our html, we wrap text in spans for translation if there are siblings, so innerHTML or textContent is mostly safe.
            el.innerHTML = translations[lang][key];
        }
    });

    // Update active state in language selector
    document.querySelectorAll('.lang-btn').forEach(btn => {
        btn.classList.remove('active');
        if (btn.getAttribute('data-lang') === lang) {
            btn.classList.add('active');
        }
    });
}

// Set language on load
document.addEventListener('DOMContentLoaded', () => {
    const savedLang = localStorage.getItem('qums_lang') || 'en';
    changeLanguage(savedLang);
});
